/*
 * dump-identifiers.c --
 *
 *      Operations to dump flat lists of SMI module information.
 *
 * Copyright (c) 2000 Frank Strauss, Technical University of Braunschweig.
 * Copyright (c) 2000 J. Schoenwaelder, Technical University of Braunschweig.
 *
 * See the file "COPYING" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * @(#) $Id: dump-identifiers.c,v 1.3 2000/08/18 12:06:17 strauss Exp $
 */

/*
 * TODO: - always generate node output in OID order
 *       - smarter layout in columns
 *	 - add a type column which contains the type
 *	   for nodes or the parent type for typedefs
 */

#include <config.h>

#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <time.h>

#include "smi.h"
#include "smidump.h"



static char *getNodekindString(SmiNodekind nodekind)
{
    return
	(nodekind == SMI_NODEKIND_NODE)         ? "node" :
	(nodekind == SMI_NODEKIND_SCALAR)       ? "scalar" :
	(nodekind == SMI_NODEKIND_TABLE)        ? "table" :
	(nodekind == SMI_NODEKIND_ROW)	        ? "row" :
	(nodekind == SMI_NODEKIND_COLUMN)	? "column" :
	(nodekind == SMI_NODEKIND_NOTIFICATION) ? "notification" :
	(nodekind == SMI_NODEKIND_GROUP)        ? "group" :
	(nodekind == SMI_NODEKIND_COMPLIANCE)   ? "compliance" :
	(nodekind == SMI_NODEKIND_CAPABILITIES) ? "capabilities" :
					          "-";
}



static char *getOidString(SmiSubid *o, int l)
{
    static char s[200];
    int i;
    
    for (i = 0, s[0] = 0; i < l; i++) {
	sprintf(&s[strlen(s)], "%d.", o[i]);
    }
    s[strlen(s)-1] = 0;
    return s;
}



static void printIdentifiers(SmiModule *module)
{
    SmiNode *smiNode;
    SmiType *smiType;

    for (smiType = smiGetFirstType(module);
	 smiType;
	 smiType = smiGetNextType(smiType)) {
	printf("%-15s %-20s %-12s %-30s\n",
	       module->name, smiType->name,
	       "typedef",
	       "-");
    }
    
    for (smiNode = smiGetFirstNode(module, SMI_NODEKIND_ANY);
	 smiNode;
	 smiNode = smiGetNextNode(smiNode, SMI_NODEKIND_ANY)) {
	printf("%-15s %-20s %-12s %-30s\n",
	       module->name, smiNode->name,
	       getNodekindString(smiNode->nodekind),
	       getOidString(smiNode->oid, smiNode->oidlen));
    }
}



void dumpIdentifiers(Module *module)
{
    SmiModule *smiModule;
    Module    *mPtr;
    int	      unite;

    smiModule = module->smiModule;
    unite = module->flags & SMIDUMP_FLAG_UNITE;

    if ((smiModule && !unite) || (!smiModule && unite)) {
	if (! (module->flags & SMIDUMP_FLAG_SILENT)) {
	    printf("# %s list of identifiers (generated by smidump "
		   SMI_VERSION_STRING ")\n\n",
		   unite ? "united" : smiModule->name);
	}
    }

    if (smiModule && !unite) {
	printIdentifiers(smiModule);
    }

    if (!smiModule && unite) {
	for (mPtr = module; mPtr; mPtr = mPtr->nextPtr) {
	    printIdentifiers(mPtr->smiModule);
	}
    }
}
