.TH miblint 1 "Aug 1998" "MIB Tools"
.SH NAME
miblint \- syntax and semantics checks of SMIv1/v2 MIB files
.SH SYNOPSIS
.B miblint
[
.B "-rRsSvVyY"
] [
.BI "-l level"
] [
.BI "-d level"
] [
.BI "-c config"
] [
.BI "-m module"
]
.BI "file ..."
.SH NOTE
This is work in progress. Don't expect this to be suited for
productional use.
.SH DESCRIPTION
The
.B miblint
program is used to check MIB
.BR file s
for syntax errors and also
semantics at some degree. Both, SMIv1 and SMIv2 style MIB modules
are supported. SIMv2 MIB modules are identified by importing
anything from the SNMPv2-SMI module.
.PP
The rules that
.B miblint
is based on, are taken from RFC 1902, RFC 1903 and RFC 1904.
(Actually, some refinements are under way in form of three
internet-drafts that are expected to become full standard RFCs and
obsolete the above mentiones RFC documents.)
.br
.SH OPTIONS
.TP
.B "-r"
Recursively report errors (and statistic, if enabled) on imported
modules.
.TP
.B "-R"
Don't recursively report errors and statistic (default).
.TP
.B "-s"
Report some per module statistics.
.TP
.B "-S"
Don't report statistics (default).
.TP
.B "-v"
On errors, do print the current line of input after the error message
and a marker pointing to the actual token in the input stream. Note,
that the corresponding point of error usually lies before this marker.
.TP
.B "-V"
Don't print error lines (default).
.TP
.B "-y"
Activate the yydebug output of bison. This is only of interest for
.B miblint
debugging purpose.
.TP
.B "-Y"
Deactivate yydebug output of bison (default).
.TP
.BI "-d level"
Print debugging messages at the given level.
.TP
.BI "-l level"
Report errors and warnings up to the given
.BR level .
A higher level shows more warnings. The actual levels are:
.sp
.nf
 0   internal error, no recovery possible,
 1   major SMI error, recovery somehow possible but
     may lead to severe problems,
 2   SMI error, probably tolerated by some
     implementations,
 3   SMI error, tolerated by many implementations,
 4   something which is recommended to be changed,
     but no read error,
 5   something that might be ok, but might not be
     recommended under some circumstances
.fi
.sp
Higher levels are actually not used and lead to the same effects as
level 5. Note, that errors up to level 3 are real errors and have to
be fixed by the responsible author. Level 3 is the default level.
.TP
.BI "-c config"
Read some configuration from the file
.BR config .
Besides empty lines and lines starting with a `#' character are
ignored. The known configuration directives are:
.sp
.nf
 directory <dir>         Makes miblint try to look
                         up MIB module files in the
                         specified directory.
 module <module> <file>  Makes miblint look for
                         the specified module in
                         the specified file. This
                         is not needed when those
                         two names are equal. 
 preload <module>        Makes miblint preload all
                         declarations from the
                         specified module.
 importloging <0|1>      see options -r, -R.
 statistics <0|1>        see options -s, -S.
 errorlines <0|1>        see options -v, -V.
 yydebug <0|1>           see options -y, -Y.
 loglevel <level>        see option -l.
.fi
.sp
.TP
.BI "-m module"
Read just the given MIB
.B module
from the input file, instead of the whole file
which might contain multiple MIB modules.
.SH "SEE ALSO"
http://www.ibr.cs.tu-bs.de/~strauss/sming/
.br
.BR scotty ( 1 ),
.BR mosy ( 1 ),
.BR smicng ( 1 ).
.SH "BUGS"
Definetely too many to mention at this point. Anyway, bug reports
are welcome.
.br
.SH "AUTHOR"
Frank Strauss (strauss@ibr.cs.tu-bs.de), TU Braunschweig.
.br
