/*
 * dump-sming.c --
 *
 *      Operations to dump SMIng module information.
 *
 * Copyright (c) 1998 Technical University of Braunschweig.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * @(#) $Id: dump-sming.c,v 1.1 1999/03/12 15:58:58 strauss Exp $
 */

#include <sys/types.h>
#include <unistd.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>

#include "error.h"
#include "util.h"
#include "data.h"
#include "smi.h"



static char *
getOidString(modulename, oid)
    char *modulename;
    char *oid;
{
    smi_namelist *namelist;
    static char s[SMI_MAX_OID+1];

    s[0] = 0;

    namelist = smiGetNames(oid, modulename);
    if (namelist) {
	printf ("X%sX", namelist->namelist);
    }
    return s;
}



static void
printMultilineString(s)
    const char *s;
{
    int i;
    
    printf("       \"");
    if (s) {
	for (i=0; i < strlen(s); i++) {
	    if (s[i] != '\n') {
		printf("%c", s[i]);
	    } else {
		printf("\n");
		printf("        ");
	    }
	}
    }
    printf("\"");
}



static void
printImports()
{

}



void
dumpSming(modulename)
    char *modulename;
{
    smi_fullname *fullname2;
    smi_module *module;
    smi_node *node;
    smi_type *type;
    smi_macro *macro;
    smi_namelist *namelist;

    module = smiGetModule(modulename, 1);
    if (!module) {
	printError(NULL, ERR_MODULE_NOT_FOUND, modulename);
    } else {
	printf("//\n");
	printf("// This module has been generated by smidump. Do not edit.\n");
	printf("//\n");
	printf("module %s ", module->name);
	if (strlen(module->oid)) {
	    printf("%s ", module->oid);
	}
	printf("{\n");
	printf("\n");

	printImports();

	if (strlen(module->oid)) {
	    printf("    oid                 %s;\n",
		   getOidString(modulename, module->oid));
	    printf("\n");
	    printf("    organization        \n");
	    printMultilineString(module->organization);
	    printf(";\n");
	    printf("\n");
	    printf("    contact             \n");
	    printMultilineString(module->contactinfo);
	    printf(";\n");
	    printf("\n");
	    printf("    description         \n");
	    printMultilineString(module->description);
	    printf(";\n");
	    printf("\n");
	    
	    
	}
	
	/* printTypedefs(); */
	/* printObjects(); */
	/* printNotifications(); */
	/* printGroups(); */
	/* printCompliances(); */	
	printf("};\n");
    }
#if 0
    if (root) {
	if (root != rootNode) {
	    if ((root->flags & FLAG_MODULE) &&
		(root->firstObject->descriptor &&
		 root->parent->firstObject->descriptor)) {
		sprintf(s, "%s.%d",
			root->parent->firstObject->descriptor->name,
			root->subid);
		if (root->firstObject->decl == SMI_DECL_OBJECTTYPE) {
		    printf("%-19s %-19s %-15s %-15s %s\n",
			   root->firstObject->descriptor->name,
			   s,
			   "<type>",
			   smiStringAccess(root->firstObject->access),
			   smiStringStatus(root->firstObject->status));
		} else {
		    printf("%-19s %s\n",
			   root->firstObject->descriptor->name,
			   s);
		}
	    }
	}
	for (c = root->firstChild; c; c = c->next) {
	    dumpMosy(c);
	}
    }
#endif
}
