/*
 * This C file has been generated by smidump 0.2.8.
 * It is intended to be used with the NET SNMP agent.
 *
 * This C file is derived from the MAU-MIB module.
 *
 * $Id$
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "mau_mib.h"

#include <asn1.h>
#include <snmp.h>
#include <snmp_api.h>
#include <snmp_impl.h>
#include <snmp_vars.h>

static oid mau_mib_caps[] = {0,0};

void init_mau_mib(void)
{
}

void deinit_mau_mib()
{
    unregister_sysORTable(mau_mib_caps, sizeof(mau_mib_caps));
}

int term_mau_mib()
{
    deinit_mau_mib();
    return 0;
}

