/*
 * This Java file has been generated by smidump 0.2.13. Do not edit!
 * It is intended to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class represents a Java AgentX (JAX) implementation of
    the table row etherStats2Entry defined in RMON2-MIB.

    @version 1
    @author  smidump 0.2.13
    @see     AgentXTable, AgentXEntry
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class EtherStats2Entry extends AgentXEntry
{

    protected long etherStatsDroppedFrames = 0;
    protected long etherStatsCreateTime = 0;

    public EtherStats2Entry()
    {

    }

    public long get_etherStatsDroppedFrames()
    {
        return etherStatsDroppedFrames;
    }

    public long get_etherStatsCreateTime()
    {
        return etherStatsCreateTime;
    }

}

