/*
 * This Java file has been generated by smidump 0.2.8. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the scalar group ifMIBObjects defined in IF-MIB.
 */

import java.util.Vector;
import java.util.Enumeration;
import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;

public class IfMIBObjectsImpl extends IfMIBObjects
{

    public long get_ifTableLastChange()
    {
        return ifTableLastChange;
    }

    public long get_ifStackLastChange()
    {
        return ifStackLastChange;
    }

}

