/*
 * This Java file has been generated by smidump 0.2.14. It
 * is intended to be edited by the application programmer and
 * to be used within a Java AgentX sub-agent environment.
 *
 * $Id$
 */

/**
    This class extends the Java AgentX (JAX) implementation of
    the table row tokenRingPStats2Entry defined in RMON2-MIB.
 */

import jax.AgentXOID;
import jax.AgentXSetPhase;
import jax.AgentXResponsePDU;
import jax.AgentXEntry;

public class TokenRingPStats2EntryImpl extends TokenRingPStats2Entry
{

    // constructor
    public TokenRingPStats2EntryImpl()
    {
        super();
    }

    public long get_tokenRingPStatsDroppedFrames()
    {
        return tokenRingPStatsDroppedFrames;
    }

    public long get_tokenRingPStatsCreateTime()
    {
        return tokenRingPStatsCreateTime;
    }

}

