augment.yang:8: anyxml 'test' is not allowed as a child node of the target container 'interfaces'
augment.yang:22: case 'test' is not allowed as a child node of the target container 'c'
augment.yang:26: leaf 'test' is not allowed as a child node of the target choice 'test-choice'
as:d' does not specify a valid target node
as:tets' does not specify a valid target node
augment.yang:51: augment instantiotion causes duplication of identifier 'ifIndex'
