/*
 * dump-sming.c --
 *
 *      Operations to dump SMIng module information.
 *
 * Copyright (c) 1998 Technical University of Braunschweig.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * @(#) $Id: dump-sming.c,v 1.2 1999/03/15 11:07:16 strauss Exp $
 */

#include <sys/types.h>
#include <unistd.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>

#include "smi.h"



static char *
getOidString(modulename, object)
    char	 *modulename;
    char	 *object;
{
    smi_node     *smiNode;
    static char	 s[SMI_MAX_OID+1];

    s[0] = 0;

    smiNode = smiGetNode(object, modulename);
    if (smiNode) {
	sprintf (s, "%s_TODO", smiNode->oid);
    }
    return s;
}



static void
printMultilineString(s)
    const char *s;
{
    int i;
    
    printf("       \"");
    if (s) {
	for (i=0; i < strlen(s); i++) {
	    if (s[i] != '\n') {
		printf("%c", s[i]);
	    } else {
		printf("\n");
		printf("        ");
	    }
	}
    }
    printf("\"");
}



static void
printImports()
{

}



void
dumpSming(modulename)
    char	 *modulename;
{
    smi_module	 *smiModule;
#if 0
    smi_fullname *smiFullname;
    smi_node	 *smiNode;
    smi_type	 *smiType;
    smi_macro	 *smiMacro;
    smi_namelist *smiNamelist;
#endif
    
    smiModule = smiGetModule(modulename);
    if (!smiModule) {
	fprintf(stderr, "Cannot locate module `%s'\n", modulename);
    } else {
	printf("//\n");
	printf("// This module has been generated by smidump. Do not edit.\n");
	printf("//\n");
	printf("module %s ", smiModule->name);
	if (strlen(smiModule->object)) {
	    printf("%s ", smiModule->object);
	}
	printf("{\n");
	printf("\n");

	printImports();

	if (strlen(smiModule->object)) {
	    printf("    oid                 %s;\n",
		   getOidString(modulename, smiModule->object));
	    printf("\n");
	    printf("    organization        \n");
	    printMultilineString(smiModule->organization);
	    printf(";\n");
	    printf("\n");
	    printf("    contact             \n");
	    printMultilineString(smiModule->contactinfo);
	    printf(";\n");
	    printf("\n");
	    printf("    description         \n");
	    printMultilineString(smiModule->description);
	    printf(";\n");
	    printf("\n");
	    printf("    reference           \n");
	    printMultilineString(smiModule->reference);
	    printf(";\n");
	    printf("\n");
	    
	    
	}
	
	/* printTypedefs(); */
	/* printObjects(); */
	/* printNotifications(); */
	/* printGroups(); */
	/* printCompliances(); */	
	printf("};\n");
    }
}
