/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "smi.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#include <signal.h>
#include <sys/types.h>
#include <memory.h>
#include <stropts.h>
#include <netconfig.h>
#include <sys/resource.h> /* rlimit */
#include <syslog.h>

#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120

/*
 * smi.x -- ( smi.h smi_clnt.c smi_svc.c smi_xdr.c )
 *
 *      RPC interface definition for the SMI service.
 *
 * Copyright (c) 1998 Technical University of Braunschweig.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * @(#) $Id: smi.x,v 1.7 1998/11/19 19:44:03 strauss Exp $
 */

static int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

static void
closedown(sig)
	int sig;
{
	if (_rpcsvcstate == _IDLE && _rpcsvccount == 0) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;
		struct t_info tinfo;

		if (!t_getinfo(0, &tinfo) && (tinfo.servtype == T_CLTS))
			exit(0);
		if (size == 0) {
			struct rlimit rl;

			rl.rlim_max = 0;
			getrlimit(RLIMIT_NOFILE, &rl);
			if ((size = rl.rlim_max) == 0) {
				return;
			}
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= 1)
			exit(0);
	} else
		_rpcsvcstate = _IDLE;

	(void) signal(SIGALRM, (void(*)()) closedown);
	(void) alarm(_RPCSVC_CLOSEDOWN/2);
}

static void
smiprog_1(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		smi_getspec smiproc_module_1_arg;
		smi_getspec smiproc_node_1_arg;
		smi_getspec smiproc_type_1_arg;
		smi_fullname smiproc_macro_1_arg;
		smi_fullname smiproc_names_1_arg;
		smi_fullname smiproc_children_1_arg;
		smi_fullname smiproc_members_1_arg;
		smi_fullname smiproc_parent_1_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	_rpcsvccount++;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, xdr_void,
			(char *)NULL);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;

	case SMIPROC_MODULE:
		_xdr_argument = xdr_smi_getspec;
		_xdr_result = xdr_smi_module;
		local = (char *(*)()) smiproc_module_1;
		break;

	case SMIPROC_NODE:
		_xdr_argument = xdr_smi_getspec;
		_xdr_result = xdr_smi_node;
		local = (char *(*)()) smiproc_node_1;
		break;

	case SMIPROC_TYPE:
		_xdr_argument = xdr_smi_getspec;
		_xdr_result = xdr_smi_type;
		local = (char *(*)()) smiproc_type_1;
		break;

	case SMIPROC_MACRO:
		_xdr_argument = xdr_smi_fullname;
		_xdr_result = xdr_smi_macro;
		local = (char *(*)()) smiproc_macro_1;
		break;

	case SMIPROC_NAMES:
		_xdr_argument = xdr_smi_fullname;
		_xdr_result = xdr_smi_namelist;
		local = (char *(*)()) smiproc_names_1;
		break;

	case SMIPROC_CHILDREN:
		_xdr_argument = xdr_smi_fullname;
		_xdr_result = xdr_smi_namelist;
		local = (char *(*)()) smiproc_children_1;
		break;

	case SMIPROC_MEMBERS:
		_xdr_argument = xdr_smi_fullname;
		_xdr_result = xdr_smi_namelist;
		local = (char *(*)()) smiproc_members_1;
		break;

	case SMIPROC_PARENT:
		_xdr_argument = xdr_smi_fullname;
		_xdr_result = xdr_smi_fullname;
		local = (char *(*)()) smiproc_parent_1;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, _xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	return;
}

main(int argc, char *argv[])
{
	pid_t pid;
	int i;

	smi_svc_init(argc, argv);
	    
	(void) sigset(SIGPIPE, SIG_IGN);

	/*
	 * If stdin looks like a TLI endpoint, we assume
	 * that we were started by a port monitor. If
	 * t_getstate fails with TBADF, this is not a
	 * TLI endpoint.
	 */
	if (t_getstate(0) != -1 || t_errno != TBADF) {
		char *netid;
		struct netconfig *nconf = NULL;
		SVCXPRT *transp;
		int pmclose;

		_rpcpmstart = 1;
		openlog("smi", LOG_PID, LOG_DAEMON);

		if ((netid = getenv("NLSPROVIDER")) == NULL) {
		/* started from inetd */
			pmclose = 1;
		} else {
			if ((nconf = getnetconfigent(netid)) == NULL)
				_msgout("cannot get transport info");

			pmclose = (t_getstate(0) != T_DATAXFER);
		}
		if ((transp = svc_tli_create(0, nconf, NULL, 0, 0)) == NULL) {
			_msgout("cannot create server handle");
			exit(1);
		}
		if (nconf)
			freenetconfigent(nconf);
		if (!svc_reg(transp, SMIPROG, SMIVERS, smiprog_1, 0)) {
			_msgout("unable to register (SMIPROG, SMIVERS).");
			exit(1);
		}
		if (pmclose) {
			(void) signal(SIGALRM, (void(*)()) closedown);
			(void) alarm(_RPCSVC_CLOSEDOWN/2);
		}
		svc_run();
		exit(1);
		/* NOTREACHED */
	}	else {
#ifndef RPC_SVC_FG
		int size;
		struct rlimit rl;
		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		rl.rlim_max = 0;
		getrlimit(RLIMIT_NOFILE, &rl);
		if ((size = rl.rlim_max) == 0)
			exit(1);
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/null", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		setsid();
		openlog("smi", LOG_PID, LOG_DAEMON);
#endif
	}
	if (!svc_create(smiprog_1, SMIPROG, SMIVERS, "netpath")) {
		_msgout("unable to create (SMIPROG, SMIVERS) for netpath.");
		exit(1);
	}

	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
