/*
 * This C file has been generated by smidump 0.2.10.
 * It is intended to be used with the NET SNMP agent.
 *
 * This C file is derived from the IF-MIB module.
 *
 * $Id$
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "if-mib.h"

#include <asn1.h>
#include <snmp.h>
#include <snmp_api.h>
#include <snmp_impl.h>
#include <snmp_vars.h>

static oid if_mib_caps[] = {0,0};

void init_if_mib(void)
{
}

void deinit_if_mib()
{
    unregister_sysORTable(if_mib_caps, sizeof(if_mib_caps));
}

int term_if_mib()
{
    deinit_if_mib();
    return 0;
}

