/*
 * This C file has been generated by smidump 0.2.8.
 * It is intended to be used with the NET SNMP agent.
 *
 * This C file is derived from the SNMPv2-MIB module.
 *
 * $Id$
 */

#include <stdio.h>
#include <string.h>
#include <malloc.h>

#include "snmpv2_mib.h"

#include <asn1.h>
#include <snmp.h>
#include <snmp_api.h>
#include <snmp_impl.h>
#include <snmp_vars.h>

static oid snmpv2_mib_caps[] = {0,0};

void init_snmpv2_mib(void)
{
}

void deinit_snmpv2_mib()
{
    unregister_sysORTable(snmpv2_mib_caps, sizeof(snmpv2_mib_caps));
}

int term_snmpv2_mib()
{
    deinit_snmpv2_mib();
    return 0;
}

